### ISSUE TITLE
Unable To Save Changes

### ISSUE THREAD

**Issue by Cykreet** [get-atlas/issues#1]
### Steps to reproduce

(This does indeed happen on most modules)
1. Head to the moderation module.
2. Disable all moderation commands.

### Expected behavior
Should disable all moderation commands and be able to save changes.

### Actual behavior
Unable to save or reset changes.

### Environment
- Browser(s): 
<img src="https://user-images.githubusercontent.com/45258926/50056306-9c270c80-015a-11e9-83f9-7b08d823bcd7.png" alt="Opera" width="10" height="10"> [Opera](https://www.opera.com) Version 56.0.3051.116, 
<img src="https://user-images.githubusercontent.com/45258926/50056358-5f0f4a00-015b-11e9-9feb-db5bcbf46f54.png" alt="Opera" width="10" height="10"> [Google Chrome](https://www.google.com/chrome/) Version 71.0.3578.98 (Official Build) (64-bit)
- Operating System: Windows 10 (64-bit)
- Server ID: 490538791958872075
  
- Error messages (if any): 
```
ValidationError: "body" must be one of [[object Object]]
```

### Additional information
![Screenshot of the above mentioned, error message.](https://user-images.githubusercontent.com/45258926/50051336-4168c300-0110-11e9-8a99-c9196f31bff5.png)

- The Dashboard in general, when it comes to switching commands on and off, is very buggy.
- This "bug" has also been tested on several browsers listed above.

<br />

### Additional checks

- [x] I have been able to reproduce the bug at least twice before submitting this bug report.
- [x] This bug happens both before and after I clear my cache and have waited 30 seconds.
- [x] This bug does not exist on Trello.

**Comment by NotSylver** [comment]
It may have taken 3 days, but I figured it out from the shitty Joi error message. Fixed in the next patch.
