### ISSUE TITLE
(Small Issue) Embed Builder Color/ Colour Picker

### ISSUE THREAD

**Issue by Cykreet** [get-atlas/issues#2]
### Steps to reproduce

1. Head to the embed builder on the v8 dashboard.
2. Set color/ colour to [`#0062FF`](https://www.color-hex.com/color/0062ff).

### Expected behavior
Should change the embedded message color/ colour to the chosen color/ colour.

### Actual behavior
Sets the color/ colour to a bright green. ([`#00FF3B`](https://www.color-hex.com/color/00ff3b), may not be exact hex)

### Environment
- Browser(s): 
<img src="https://user-images.githubusercontent.com/45258926/50056306-9c270c80-015a-11e9-83f9-7b08d823bcd7.png" alt="Opera" width="10" height="10"> [Opera](https://www.opera.com) Version 56.0.3051.116, 
<img src="https://user-images.githubusercontent.com/45258926/50056358-5f0f4a00-015b-11e9-9feb-db5bcbf46f54.png" alt="Opera" width="10" height="10"> [Google Chrome](https://www.google.com/chrome/) Version 71.0.3578.98 (Official Build) (64-bit)
- Operating System: Windows 10 (64-bit)
- Server ID: 490538791958872075
  
- Error messages (if any): 
```

```

### Additional information
![opera_2018-12-20_08-12-27](https://user-images.githubusercontent.com/45258926/50267251-e47a4f00-0426-11e9-8a78-7158b4dcef45.png)
![discord_2018-12-20_08-12-36](https://user-images.githubusercontent.com/45258926/50267235-daf0e700-0426-11e9-9d0a-fee5dd335fa7.png)
![discord_2018-12-20_08-12-42](https://user-images.githubusercontent.com/45258926/50267244-e04e3180-0426-11e9-874d-d19e28e9a3bf.png)

- The color/ colour picker itself has no issues, but when switching to the hex provided above, not sure if this applies to other colors/ colours, it defaults green.

<br />

### Additional checks

- [x] I have been able to reproduce the bug at least twice before submitting this bug report.
- [x] This bug happens both before and after I clear my cache and have waited 30 seconds.
- [x] This bug does not exist on Trello.

**Comment by NotSylver** [comment]
Fixed in the next release (8.0.15).
