### ISSUE TITLE
Visual Glitches On Actions Module

### ISSUE THREAD

**Issue by Cykreet** [get-atlas/issues#3]
### Steps to reproduce
1. Head to Action module.
2. Change `Action One`'s delivery channel to anything other than `Invocation Channel`.

### Expected behavior
*Should* display the delivery channel of choice and *not* `Invocation Channel`.

### Actual behavior
Displays `Invocation Channel`.

### Environment
- Browser(s): 
<img src="https://user-images.githubusercontent.com/45258926/50056306-9c270c80-015a-11e9-83f9-7b08d823bcd7.png" alt="Opera" width="10" height="10"> [Opera](https://www.opera.com) Version 56.0.3051.116, 
<img src="https://user-images.githubusercontent.com/45258926/50056358-5f0f4a00-015b-11e9-9feb-db5bcbf46f54.png" alt="Opera" width="10" height="10"> [Google Chrome](https://www.google.com/chrome/) Version 71.0.3578.98 (Official Build) (64-bit)
- Operating System: Windows 10 (64-bit)
- Server ID: 365569515419074562
  
- Error messages (if any): 
```

```

### Additional information
Before:
![Before](https://user-images.githubusercontent.com/45258926/50486805-eaaa9580-09fb-11e9-9fb6-a68a6a7fe77e.png)
After:
![After](https://user-images.githubusercontent.com/45258926/50486805-eaaa9580-09fb-11e9-9fb6-a68a6a7fe77e.png)

Keep in mind this "bug" is purely a visual glitch and does not limit any functionality.

<br />

### Additional checks

- [x] I have been able to reproduce the bug at least twice before submitting this bug report. (Including confirmation from another admin, *node*)
- [x] This bug happens both before and after I clear my cache and have waited 30 seconds.
- [x] This bug does not exist on Trello.

**Comment by NotSylver** [comment]
I could not recreate this on the current version (8.0.33). There has been many changes to actions recently, so it was probably just inadvertently fixed. If it's still an issue, re-open this issue.
